
# Creating this compose file to build all images and run all containers
# in on go.
version: '3.8'
services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    environment:
      DISCOVERY_SERVER: discovery-service
    depends_on:
      - discovery-service
    ports:
      - "8080:8080"
  product-service:
    build: ./product-service
    container_name: product-service
    environment:
      DISCOVERY_SERVER: discovery-service
    depends_on:
      - discovery-service
      - gateway-service
  order-service:
    build: ./order-service
    container_name: order-service
    environment:
      DISCOVERY_SERVER: discovery-service
    depends_on:
      - discovery-service
      - gateway-service
