debug: true
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
#      default-filters:
#        - RewritePath=([^/])$, $1/ #Rewrite /
      mvc:
        routes:
          - id: order-service-routes
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/api/orders/**
              - Method=POST,OPTIONS
            filters:
              - RewritePath=/api/orders/(?<segment>.*), /orders/$\{segment}
          - id: product-service-route
            uri: lb://PRODUCT-SERVICE
            predicates:
              - Path=/api/products/**
              - Method=GET,POST,OPTIONS
            filters:
              - RewritePath=/api/products/(?<segment>.*), /products/$\{segment}

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVER:localhost}:8761/eureka
